language: node_js
node_js:
  - "6"
addons:
  firefox: "58.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm test
  - npm run package
  - npm run build
  - npm run ambassador:build
  - node e2e/web-server & npm run test:e2e
 
 
